version: '3.8'

services:
  kasa:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/kasa.db
    restart: unless-stopped
    networks:
      - kasa-network

networks:
  kasa-network:
    driver: bridge 